### ISSUE TITLE
0.2.0 Compatibility

### ISSUE THREAD

**Issue by cduvall** [m4cx/kraken-wsapi-dotnet#26]
After the update to Websockets version 0.20, the API no longer works as intended.

https://blog.kraken.com/post/2341/new-version-of-kraken-websockets-public-api-goes-live-may-30/

Depending on my priorities, I may be able to fork this and handle the update if someone isn't already working toward it.

**Comment by drmrboyc** [comment]
I'm interested in getting a working version of this api again!

**Comment by drmrboyc** [comment]
> After the update to Websockets version 0.20, the API no longer works as intended.
> 
> https://blog.kraken.com/post/2341/new-version-of-kraken-websockets-public-api-goes-live-may-30/
> 
> Depending on my priorities, I may be able to fork this and handle the update if someone isn't already working toward it.

Here is a quick and easy fix until the author of this great little api updates it to support the changes.

The reason for the break in functionality is that Kraken added two more parameters into the messages we now receive in the ticker, ohlc, spread, trade, and book subscriptions. What was once a message that could be parsed into two array items (channel ID, and message payload [contains all the data]), now must be parsed as four array items. 

Inside the method CreateFromString(), in each of the classes TickerMessage, SpreadMessage, OhlcMessage, TradesMessage, and BookSnapshotMessage, Maik parses the incoming message by turning it into a JArray and using the '.First' and '.Last' parameters to refer to the ChannelId and Message Payload respectively.

**As a quick hack to restore functionality, simply change the '.Last' property reference to '[1]'. This will point correctly to the message payload, and not the newly added string parameter.**

NOTE: Maik's implementation of CreateFromString() in BookUpdateMessage was unaffected by the 0.2.0 update as he is able to pull JArray elements out by name and not position.

_Because this is a quick little hack and does not add functionality to catch these new parameters, I didn't think this quick fix was worth a fork._

**Comment by m4cx** [comment]
@cduvall many thanks to you for raising this issue. I was not aware of this new update. Also my notifications got lost in my inbox. I will work on this asap. 

@drmrboyc thanks for providing this "fix manual".

**Comment by m4cx** [comment]
@cduvall & @drmrboyc 
I provided a [new pre-release](https://www.nuget.org/packages/Kraken.WebSockets/0.1.1-b287) that should work fine with the 0.2.0 version for now. In the next steps I will introduce the new information to the messages. But AFAIK this would affect the external API of the library an will result in a 0.2.0 version of the library. 

My personal goal for the 0.2.0 was to also improve the handling of creating a client instance. So please be patient. 

I will test the current pre-release mentioned before and provide a final 0.1.1 in the next days. I really apprechiate your feedback.

**Comment by m4cx** [comment]
[Fix released](https://www.nuget.org/packages/Kraken.WebSockets/0.1.1)
