### ISSUE TITLE
Support Authentication for private messages

### ISSUE THREAD

**Issue by m4cx** [m4cx/kraken-wsapi-dotnet#41]
[Authentication ](https://www.kraken.com/features/websocket-api-beta#authentication) (for Private Messages, preview only)

The API client must request an authentication "token" via the following REST API endpoint "getWebSocketsToken" to connect to WebSockets Private endpoints. The token expires every 60 minutes. Please reach out to your Account Manager to receive the token endpoint url to connect to test environment.

**Comment by drmrboyc** [comment]
Just a quick FYI, it looks like Kraken changed the authentication "token" to no longer expire after 60 minutes (as long as it's used within 15 minutes of creation).

According to [https://www.kraken.com/features/websocket-api#authentication](https://www.kraken.com/features/websocket-api#authentication):

> The API client must request an authentication "token" via the following REST API endpoint "GetWebSocketsToken" to connect to WebSockets Private endpoints. The token should be used within 15 minutes of creation. The token does not expire once a connection to a WebSockets API private message (openOrders or ownTrades) is maintained. 

Of course, Kraken updated it to no longer expire right after I added an event that bubbles up from KrakenWebSocket through KrakenApiClient and fires based off an internally maintained 55 minute timer. I added it so the user could provide a new token (from their REST handling framework) without having to track expiry of the previous tokens. Yes yes...I know it doesn't make any sense at all to put it there...but my code never makes sense xD!
