### ISSUE TITLE
No new information pushes through after a few seconds

### ISSUE THREAD

**Issue by R00iBaard** [m4cx/kraken-wsapi-dotnet#44]
Hey, 

Thanks so much for sharing this! Really awesome!
I am however running into issues keeping the "socket open". It starts up perfectly but then halts operation soon after. Any idea?

![image](https://user-images.githubusercontent.com/11412240/65661122-14e3bf00-e031-11e9-99d0-83619db92c69.png)

**Comment by m4cx** [comment]
Hi @R00iBaard,

I appreciate your feedback and that you are using my library. Without your code it is just guessing for me what can be the reason. 

Did you use my code example for your logic? I cancel the activity after 50 seconds.
```csharp
client.SubscriptionStatusChanged += async (sender, e) =>
{
    if (e.Message.Status == SubscriptionStatusNames.Subscribe && e.Message.ChannelId.HasValue)
    {
        await Task.Delay(50000);
        await client.UnsubscribeAsync(e.Message.ChannelId.Value);
    }
};
```
Another option could be, that no updates are sent. Could you also attach the Heartbeat-Handler to see if this is correctly handled?

Best regards
Maik

**Comment by R00iBaard** [comment]
All sorted :) Thanks for such a fast response! False alarm.
